apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-retain-storage
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
